events {}

http {
  server {
    listen 80;

    root /var/www/frontend;
    index wall.html;

    location / {
      try_files $uri $uri/ /wall.html;
    }

    location /api/ {
      proxy_pass http://backend:3000;
    }

    location /uploads/ {
      alias /var/www/uploads/;
    }
  }
}