events {
    worker_connections 1024;
}
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    client_max_body_size 20M;
    server {
        listen 80;
        server_name localhost;
        root /var/www/frontend;
        index wall.html;
        location /style/ {
            root /var/www/frontend;
            try_files $uri =404;
        }
        location /script/ {
            root /var/www/frontend;
            try_files $uri =404;
        }
        location / {
            try_files $uri $uri/ /wall.html;
        }
        location /api/ {
            proxy_pass http://backend:3000;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Host $http_host;
        }
        location /uploads/ {
            alias /var/www/uploads/;
        }
    }
}